from core.exceptions import CustomException


class CPEException(CustomException):
    code = 400
    error_code = "CPE_ERROR"
    message = "Error Occured While Getting Target CPE"