from core.exceptions import CustomException


class CVEException(CustomException):
    code = 400
    error_code = "CVE_ERROR"
    message = "Error Occured While Getting Info About CVE"